import type { Property, Agent, Inquiry } from "./types";

// ─────────────────────────────────────────────
// Mock Agents
// ─────────────────────────────────────────────

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    userId: "user-agent-1",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@brandestate.com",
    phone: "+1 (555) 019-2834",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    bio: "Sarah is a luxury real estate expert with over 12 years of experience representing buyers and sellers of elite properties in Beverly Hills and Malibu. She has been featured in top real estate publications.",
    specializations: ["villa", "house", "apartment"],
    licenseNumber: "CA-BRE-0198425",
    activeListings: 15,
    totalSales: 142,
    rating: 4.9,
    reviewCount: 94,
    joinedAt: "2018-04-12T00:00:00.000Z",
  },
  {
    id: "agent-2",
    userId: "user-agent-2",
    name: "David Chen",
    email: "david.chen@brandestate.com",
    phone: "+1 (555) 014-9821",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80",
    bio: "David specializes in contemporary urban penthouses, smart homes, and high-rise condominiums. His data-driven approach and marketing expertise make him a favorite among tech founders and investors.",
    specializations: ["apartment", "commercial"],
    licenseNumber: "NY-BRE-0205814",
    activeListings: 8,
    totalSales: 89,
    rating: 4.8,
    reviewCount: 61,
    joinedAt: "2020-09-15T00:00:00.000Z",
  },
  {
    id: "agent-3",
    userId: "user-agent-3",
    name: "Elena Rostova",
    email: "elena.rostova@brandestate.com",
    phone: "+1 (555) 018-3729",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
    bio: "Elena brings a global perspective to commercial office spaces and high-end residential listings. Fluent in English, Spanish, and Russian, she helps international clients find their ideal properties.",
    specializations: ["villa", "commercial", "land"],
    licenseNumber: "FL-BRE-0382914",
    activeListings: 12,
    totalSales: 115,
    rating: 4.7,
    reviewCount: 78,
    joinedAt: "2019-11-01T00:00:00.000Z",
  },
];

// ─────────────────────────────────────────────
// Mock Properties
// ─────────────────────────────────────────────

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    title: "Serene Oaks Luxury Villa",
    description: "An architectural masterpiece nestled in the hills, featuring sweeping views, an infinity pool, a state-of-the-art chef's kitchen, and a private guest house. Designed with materials sourced from Italy, the villa offers true resort-style living with automated smart home systems.",
    listingType: "sale",
    propertyType: "villa",
    price: 2450000,
    location: {
      address: "1482 Oakwood Terrace",
      area: "Beverly Hills",
      city: "Los Angeles",
      lat: 34.0736,
      lng: -118.4004,
    },
    bedrooms: 5,
    bathrooms: 6,
    area: 5800,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-1",
    status: "active",
    featured: true,
    amenities: ["Swimming Pool", "Gym / Fitness Center", "Parking", "Garden / Yard", "Security System", "Air Conditioning", "Furnished"],
    yearBuilt: 2021,
    parkingSpaces: 3,
    createdAt: "2026-05-10T12:00:00.000Z",
  },
  {
    id: "prop-2",
    title: "Skyline Heights Penthouse",
    description: "Suspended in the clouds, this extraordinary penthouse offers 360-degree views of the iconic city skyline. Features include double-height ceilings, a wrap-around private terrace, a climate-controlled wine cellar, and direct elevator access.",
    listingType: "sale",
    propertyType: "apartment",
    price: 1850000,
    location: {
      address: "742 Park Avenue, Penthouse B",
      area: "Upper East Side",
      city: "New York",
      lat: 40.7694,
      lng: -73.9678,
    },
    bedrooms: 3,
    bathrooms: 3.5,
    area: 2400,
    images: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-2",
    status: "active",
    featured: true,
    amenities: ["Elevator", "Security System", "Air Conditioning", "Central Heating", "Concierge", "Rooftop Terrace", "Parking"],
    yearBuilt: 2018,
    parkingSpaces: 2,
    createdAt: "2026-05-15T09:30:00.000Z",
  },
  {
    id: "prop-3",
    title: "The Glasshouse Sanctuary",
    description: "An elegant blend of concrete, steel, and floor-to-ceiling glass creates an open-plan sanctuary that flows seamlessly into native gardens. Includes an integrated home office, pool, outdoor fireplace, and private deep-water dock access.",
    listingType: "sale",
    propertyType: "house",
    price: 3200000,
    location: {
      address: "88 Marine Parade",
      area: "Mosman",
      city: "Sydney",
      lat: -33.8291,
      lng: 151.2415,
    },
    bedrooms: 4,
    bathrooms: 4.5,
    area: 4200,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-1",
    status: "active",
    featured: true,
    amenities: ["Swimming Pool", "Parking", "Garden / Yard", "Balcony", "Security System", "Air Conditioning"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    createdAt: "2026-05-20T14:45:00.000Z",
  },
  {
    id: "prop-4",
    title: "Modern Downtown Loft",
    description: "Located in the heart of the historic warehouse district, this industrial-chic loft has exposed brick walls, timber beams, and brand new premium appliances. Just steps away from London's finest dining and tube stations.",
    listingType: "rent",
    propertyType: "apartment",
    price: 3500,
    location: {
      address: "42 Redchurch Street",
      area: "Shoreditch",
      city: "London",
      lat: 51.5246,
      lng: -0.0768,
    },
    bedrooms: 1,
    bathrooms: 1.5,
    area: 950,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-2",
    status: "active",
    featured: false,
    amenities: ["Elevator", "Furnished", "Air Conditioning", "Central Heating", "Storage Room"],
    yearBuilt: 2015,
    parkingSpaces: 0,
    createdAt: "2026-05-25T11:15:00.000Z",
  },
  {
    id: "prop-5",
    title: "Chic Urban Oasis",
    description: "A compact, ultra-modern luxury apartment with intelligent space design and spectacular city views. Fully furnished with premium Japanese furniture and smart systems, located in a quiet enclave of Shibuya.",
    listingType: "rent",
    propertyType: "apartment",
    price: 4800,
    location: {
      address: "2-chome Nanpeidaicho",
      area: "Shibuya",
      city: "Tokyo",
      lat: 35.6562,
      lng: 139.6975,
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-2",
    status: "active",
    featured: false,
    amenities: ["Elevator", "Security System", "Air Conditioning", "Furnished", "Concierge"],
    yearBuilt: 2020,
    parkingSpaces: 1,
    createdAt: "2026-05-28T16:20:00.000Z",
  },
  {
    id: "prop-6",
    title: "Suburban Family Haven",
    description: "A gorgeous, newly renovated brick family home with a huge, fenced backyard, ideal for children and pets. Highly rated school district, quiet tree-lined streets, and custom updates throughout the kitchen and master bath.",
    listingType: "sale",
    propertyType: "house",
    price: 650,
    location: {
      address: "214 Glenforest Road",
      area: "Lawrence Park",
      city: "Toronto",
      lat: 43.7251,
      lng: -79.3972,
    },
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-1",
    status: "active",
    featured: false,
    amenities: ["Parking", "Garden / Yard", "Central Heating", "Pet Friendly", "Storage Room"],
    yearBuilt: 1995,
    parkingSpaces: 2,
    createdAt: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "prop-7",
    title: "Sunset Beach Villa",
    description: "Breathtaking beachfront estate with direct white-sand beach access. Double height glass walls frame infinite ocean views. Highlights include private boat dock, massive pool deck, and outdoor kitchen perfect for hosting.",
    listingType: "rent",
    propertyType: "villa",
    price: 12000,
    location: {
      address: "18 Ocean Drive",
      area: "Key Biscayne",
      city: "Miami",
      lat: 25.6943,
      lng: -80.1636,
    },
    bedrooms: 4,
    bathrooms: 5,
    area: 3500,
    images: [
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-3",
    status: "active",
    featured: false,
    amenities: ["Swimming Pool", "Parking", "Garden / Yard", "Balcony", "Security System", "Air Conditioning", "Furnished"],
    yearBuilt: 2017,
    parkingSpaces: 4,
    createdAt: "2026-06-03T15:00:00.000Z",
  },
  {
    id: "prop-8",
    title: "Commercial Business Plaza",
    description: "Highly visible retail and premium office building in the center of Berlin's business district. Fully leased to high-quality tenants, offering immediate strong cash flow and capital appreciation potential.",
    listingType: "sale",
    propertyType: "commercial",
    price: 8900000,
    location: {
      address: "74 Friedrichstraße",
      area: "Mitte",
      city: "Berlin",
      lat: 52.5121,
      lng: 13.3892,
    },
    bedrooms: 0,
    bathrooms: 12,
    area: 15000,
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    ],
    agentId: "agent-3",
    status: "active",
    featured: false,
    amenities: ["Elevator", "Security System", "Air Conditioning", "Central Heating", "Parking", "Wheelchair Accessible"],
    yearBuilt: 2012,
    parkingSpaces: 10,
    createdAt: "2026-06-04T10:10:00.000Z",
  },
];

// ─────────────────────────────────────────────
// Mock Inquiries
// ─────────────────────────────────────────────

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: "inq-1",
    propertyId: "prop-1",
    propertyTitle: "Serene Oaks Luxury Villa",
    propertyImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=120&q=80",
    userId: "user-buyer-1",
    agentId: "agent-1",
    message: "Hello Sarah, I am highly interested in Serene Oaks. Is it possible to schedule a private viewing this Saturday afternoon?",
    status: "new",
    createdAt: "2026-06-05T14:32:00.000Z",
  },
  {
    id: "inq-2",
    propertyId: "prop-4",
    propertyTitle: "Modern Downtown Loft",
    propertyImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=120&q=80",
    guestName: "Alice Miller",
    guestEmail: "alice.miller@gmail.com",
    guestPhone: "+44 7911 123456",
    agentId: "agent-2",
    message: "Hi David, is the price of £3,500 inclusive of utility bills and council tax? Thanks!",
    status: "read",
    createdAt: "2026-06-06T09:15:00.000Z",
  },
];
